# Serves a browsable viewer for doc/openapi.yaml (generated by
# rspec-openapi from the request specs - see spec/rails_helper.rb).
# Deliberately not under Api::V1 and not < ApplicationController: this
# renders an HTML page and a YAML file, not JSON, so it doesn't belong to
# the API's versioning or shared error-envelope conventions.
class DocsController < ActionController::API
  # GET /api-docs
  def show
    render body: <<~HTML, content_type: "text/html"
      <!DOCTYPE html>
      <html>
        <head>
          <title>Socially Restless API Docs</title>
          <meta charset="utf-8" />
        </head>
        <body>
          <redoc spec-url="/api-docs/openapi.yaml"></redoc>
          <script src="https://cdn.redoc.ly/redoc/latest/bundle.js"></script>
        </body>
      </html>
    HTML
  end

  # GET /api-docs/openapi.yaml
  def openapi
    send_file Rails.root.join("doc", "openapi.yaml"), type: "application/yaml", disposition: "inline"
  end
end
